baseURL = 'https://timjozi911.github.io/'
languageCode = 'en-us'
title = 'Cool portfolio site'
theme = 'PaperMod'
favicon = "favicon.ico"

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my website."

[assets]
favicon16x16 = "/assets/favicon-16x16.png"
favicon32x32 = "/assets/favicon-32x32.png"
apple_touch_icon = "/assets/apple-touch-icon.png"
